name: ommcurso
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - basemap=1.3.7=py310h930aee4_0
  - basemap-data=1.3.6=py310h06a4308_1
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_linux64_openblas
  - blosc=1.21.4=h0f2a231_0
  - boost-cpp=1.78.0=h6582d0a_3
  - boto3=1.26.134=pyhd8ed1ab_0
  - botocore=1.29.134=pyhd8ed1ab_0
  - bottleneck=1.4.2=py310haa0f9ac_1
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.16.0=h35add3b_1015
  - cartopy=0.21.1=py310h7eb24ba_1
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=1.15.1=py310h255011f_3
  - cfitsio=4.2.0=hd9d235c_0
  - cftime=1.6.2=py310hde88566_1
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.2.1=py310h06a4308_0
  - cloudpickle=3.1.1=py310h06a4308_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cryptography=40.0.2=py310h34c0648_0
  - curl=8.0.1=h588be90_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dask=2025.5.1=py310h06a4308_0
  - dask-core=2025.5.1=py310h06a4308_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distributed=2025.5.1=py310h06a4308_0
  - eccodes=2.30.0=h95353b9_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h4a9f257_0
  - freexl=1.0.6=h166bdaf_1
  - fsspec=2025.7.0=py310he3bba80_0
  - gdal=3.7.0=py310hf0ca374_0
  - geos=3.11.2=hcb278e6_0
  - geotiff=1.7.1=h480ec47_8
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h5eee18b_1
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.0=nompi_hb72d44e_103
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=72.1=hcb278e6_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipython=8.13.2=pyh41d4057_0
  - jasper=4.0.0=h32699f2_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.6=py310h06a4308_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - json-c=0.16=hc379101_0
  - kealib=1.5.1=h3845be2_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libarchive=3.6.2=h3d51595_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=8.0.1=h588be90_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=12.2.0=h65d4601_19
  - libgdal=3.7.0=he76be6c_0
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.76.2=hebfc3b9_0
  - libglu=9.0.0=he1b5a44_1001
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=h0b41bf4_0
  - libkml=1.3.0=h37653c0_1015
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libllvm14=14.0.6=hecde1de_4
  - libnetcdf=4.9.2=nompi_hdf9a29f_104
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libpq=15.3=hbcd7760_0
  - librttopo=1.1.0=h0d5128d_13
  - libspatialite=5.0.1=h7d1ca68_25
  - libsqlite=3.41.2=h2797004_1
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.5.0=ha587672_6
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.4=hfdac1af_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.3=h4dfa4b3_0
  - llvmlite=0.43.0=py310h6a678d5_1
  - locket=1.0.0=py310h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - lzo=2.10=h516909a_1000
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-base=3.6.2=py310h945d387_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310h2b4bcf5_1
  - mkl_random=1.2.2=py310h00e6091_0
  - msgpack-python=1.1.1=py310h6a678d5_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - netcdf4=1.6.3=nompi_py310h2d0b64f_102
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numba=0.60.0=py310h5dc88bb_0
  - numexpr=2.10.1=py310hd28fd6d_0
  - numpy=1.24.3=py310hac523dd_0
  - numpy-base=1.24.3=py310h375b286_0
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.0=hd590300_3
  - packaging=25.0=py310h06a4308_1
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.2=py310h06a4308_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h065c6d2_2
  - pip=22.3.1=py310h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.05.0=hd18248d_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=h814edd5_0
  - proj=9.2.0=h8ffa02c_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pygrib=2.1.4=py310hdcc264a_7
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyproj=3.5.0=py310hb814896_1
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.11=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-lmdb=1.6.2=py310h6a678d5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=pyhd8ed1ab_0
  - s3transfer=0.6.1=pyhd8ed1ab_0
  - scipy=1.10.1=py310ha4c1d20_3
  - setuptools=65.6.3=py310h06a4308_0
  - shapely=2.0.1=py310h056c13c_1
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h9fff704_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tblib=3.1.0=py310h06a4308_0
  - tiledb=2.13.2=hd532e3d_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=1.0.0=py310h06a4308_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzcode=2023c=h0b41bf4_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xerces-c=3.2.4=h8d71039_2
  - xgrads=0.2.7=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zict=3.0.0=py310h06a4308_0
  - zipp=3.21.0=py310h06a4308_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - affine==2.4.0
      - attrs==25.3.0
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - geopandas==1.1.1
      - metpy==1.5.0
      - pandas==2.3.0
      - pint==0.22
      - pyogrio==0.11.0
      - pytz==2023.3
      - rasterio==1.4.3
      - regionmask==0.13.0
      - tzdata==2023.3
      - xarray==2025.6.1
prefix: /scripts/gpt/luiz.kondraski/.conda/envs/bam
